### ISSUE TITLE
Old version of `fontawesome`

### ISSUE THREAD

**Issue by Va1da2** [aleylara/Peli-Kiera#1]
Hi!

First, thanks for the theme!
Are you considering updating fontawesome version? I encountered this limitation as I was trying to add the `Goodreads` icon to my social list.

Thanks,
Vaidas

**Comment by aleylara** [comment]
Hi,
Updated and tested the Font Awesome for `Goodreads` and it seems to be working now. 
Let me know if that solves the issue.
Thanks!

Edit: Corrected version number to v5.15.2 latest.

**Comment by aleylara** [comment]
Hi @Va1da2 ,
I pushed couple more changes to `main.css` fixing your navigation bar titles not displaying properly on mobile platforms.

I will also do a PR to @justinmayer [pelican-themes](https://github.com/getpelican/pelican-themes) hoping it gets accepted.
But in the mean time you can pull the changes from [Peli-Kiera](https://github.com/aleylara/Peli-Kiera)

**Comment by justinmayer** [comment]
Already merged in [pelican-themes](https://github.com/getpelican/pelican-themes). 🚀

**Comment by aleylara** [comment]
@justinmayer
I am a little out of touch at the moment. 
Forgot to to include the updated README.md with that issue. 
[Lucky last](https://github.com/getpelican/pelican-themes/pull/704)
Thank you!

**Comment by Va1da2** [comment]
Thanks a lot @aleylara!

I really like this theme, great work!

**Comment by aleylara** [comment]
@Va1da2 you are welcome! 
I am glad to hear the theme is working out for you.

I just like to apologize to @justinmayer for my flaky PRs and hope that he sees my last one before I close this issue.

Thanks everyone!
