### ISSUE TITLE
Social links don't appear 

### ISSUE THREAD

**Issue by minipief** [aleylara/Peli-Kiera#3]
Hi,

Thanks for clear and stylish template. I am struggling a bit with the social icon.
They show up in other themes and not in yours.

Maybe you have an idea.

example can be seen in: docpeiffer.com

Best 
Alexander

**Comment by aleylara** [comment]
Hi @minipief,
Apologies for the late reply. My notifications were turned off.

Try going in to your `pelicanconf.py` file and replace `LinkedIn` with all lowercase`linkedin`.

```
# Social widget
SOCIAL = (
    ('linkedin', '#'),
)
```

**Comment by minipief** [comment]
Hi Aleylara,

this works great. Thank you so much. Result can be seen on docpeiffer.com

Best 
Alexander
