### ISSUE TITLE
newlines in base.html break feed URL links

### ISSUE THREAD

**Issue by arturlangner** [aleylara/Peli-Kiera#4]
In base.html https://github.com/aleylara/Peli-Kiera/blob/master/templates/base.html#L14
the URLs in the `<link>` tags in base.html can't have newlines (at least the `href="" `part) because a feed URL will not be correctly recognized by a feed reader. The `href=""` part has to be on a single line.

**Comment by aleylara** [comment]
Hi @arturlangner,
Thanks for the heads up.  
I am not able to fully test it, pls let me know if the last change was enough to fix your issue.

**Comment by arturlangner** [comment]
Yes. `88b8703` fixes it. This is exactly what I did on [my site](https://m0agx.eu). I am happy with the fix going upstream. 🙂
